env:
  browser: true
  es6: true
extends: airbnb
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules:
    import/no-unresolved: 0
    react/jsx-filename-extension: 0
    react/no-array-index-key: 0
    no-shadow: 0
    no-param-reassign: 0
    react/prop-types: 0
