export default [
  ['Starring', 'Sonequa', 'Martin-Green'],
  ['Doug', 'Jones'],
  ['Anthony', 'Rapp'],
  ['Mary', 'Wiseman'],
  ['and', 'Anson', 'Mount'],
  ['Casting By', 'Margery', 'SIMKIN, csa'],
  ['Orly', 'Sitowitz, csa'],
  ['Music and Theme by', 'Jeff', 'Russo'],
  ['Costume Designer', 'GERSHA', 'Phillips'],
  ['Visual effects supervisor', 'Jason', 'Zimmerman'],
  ['Edited By', 'Scott', 'GAMZON, A.C.E'],
  ['Production Designer', 'Tamara', 'Deverell'],
  ['Director of Photography', 'Colin', 'Hoult, c.s.c.'],
  ['Co-Producers', 'Bo', 'Yeon Kim'],
  ['Erika', 'Lippold'],
  ['Producer', 'Alan', 'McELROY'],
  ['Producer', 'April', 'Nocifora'],
  ['Produced by', 'Thom J.', 'PRETAK'],
  ['Consulting Producer', 'Akiva', 'Goldsman'],
  ['Co-Executive Producer', 'Andrew', 'Colville'],
  ['Co-Executive Producer', 'Lenny', 'Lumet'],
  ['Co-Executive Producer', 'Jordon', 'Nardino'],
  ['Co-Executive Producer', 'Ted', 'Sullivan'],
  ['Co-Executive Producer', 'Vaun', 'Wilmott'],
  ['Co-Executive Producer', 'Aaron', 'Baiers'],
  ['Executive Producer', 'Olatunde', 'Osunsanmi'],
  ['Executive Producers', 'Frank', 'Siracusa'],
  ['John', 'Weber'],
  ['Executive Producers', 'Eugene', 'Roddenberry'],
  ['Trevor', 'Roth'],
  ['Executive Producer', 'Heather', 'Kadin'],
  ['Executive Producers', 'Gretchen J.', 'Berg'],
  ['Aaron', 'Harberts'],
  ['Executive Producer', 'Alex', 'Kurtzman'],
];
