export default [
  ['Starring', 'Sonequa', 'Martin - Green'],
  ['Doug', 'Jones'],
  ['Anthony', 'Rapp'],
  ['Mary', 'Wiseman'],
  ['and', 'Anson', 'Mount'],
  ['Casting By', 'Margery', 'SIMKIN, csa'],
  ['Orly', 'Sitowitz, csa'],
  ['Music and Theme by', 'Jeff', 'Russo'],
  ['Costume Designer', 'GERSHA', 'Phillips'],
  ['Visual effects supervisor', 'Jason', 'Zimmerman'],
  ['Edited By', 'Scott', 'GAMZON, A.C.E'],
  ['Production Designer', 'Tamara', 'Deverell'],
  ['Director of Photography', 'Colin', 'Hoult, c.s.c.'],
];
