export default {
  defaults: {
    duration: 3,
    classes: ['expanding', 'expanding'],
  },
  sequence: [
    {
      x: 17,
      y: 71,
      start: 3.6,
      end: 6.6,
      classes: ['small top', 'expanding', 'expanding'],
    },
    {
      x: 70,
      y: 20,
      start: 10.6,
      end: 13.29,
    },
    {
      x: 70,
      y: 20,
      start: 13.89,
      end: 16.8,
    },
    {
      x: 70,
      y: 20,
      start: 17.5,
      end: 20.19,
    },
    {
      x: 70,
      y: 20,
      start: 20.7,
      end: 23.5,
      classes: ['small', 'expanding', 'expanding'],
    },
    {
      x: 20,
      y: 20,
      start: 27.3,
      end: 29,
      classes: ['small', 'expanding', 'expanding'],
    },
    {
      x: 80,
      y: 80,
      start: 27.3,
      end: 29,
    },
    {
      x: 51.5,
      y: 61.5,
      start: 30.7,
      end: 32.32,
      classes: ['small white', 'expanding white', 'expanding white'],
    },
    {
      x: 80,
      y: 80,
      start: 33.4,
      end: 35,
      classes: ['small', 'shrinking', 'expanding'],
    },
    {
      x: 20,
      y: 80,
      start: 36.4,
      end: 38.4,
      classes: ['small', 'shrinking', 'expanding'],
    },
    {
      x: 20,
      y: 20,
      start: 37.8,
      end: 40,
      classes: ['small', 'shrinking', 'expanding'],
    },
  ],
};
