export default {
  defaults: {
    duration: 3,
    classes: ['expanding', 'expanding'],
  },
  sequence: [
    {
      x: 17,
      y: 71,
      start: 3.6,
      end: 6.6,
      classes: ['small top', 'expanding', 'expanding'],
    },
    {
      x: 62,
      y: 20,
      start: 10.6,
      end: 13.29,
    },
    {
      x: 16,
      y: 73,
      start: 13.89,
      end: 16.8,
    },
    {
      x: 18,
      y: 70,
      start: 17.5,
      end: 20.19,
    },
    {
      x: 18,
      y: 71,
      start: 20.7,
      end: 23,
      classes: ['small', 'expanding', 'expanding'],
    },
    {
      x: 10,
      y: 9,
      start: 27.3,
      end: 29,
      classes: ['small top', 'expanding', 'expanding'],
    },
    {
      x: 58,
      y: 75,
      start: 27.3,
      end: 29,
    },
    {
      x: 51.5,
      y: 61.5,
      start: 30.7,
      end: 32.32,
      classes: ['small white', 'expanding white', 'expanding white'],
    },
    {
      x: 56,
      y: 13,
      start: 33.05,
      end: 34.3,
      classes: ['small', 'shrinking', 'expanding'],
    },
    {
      x: 46,
      y: 71,
      start: 37.5,
      end: 39.2,
      classes: ['small', 'shrinking', 'expanding'],
    },
    {
      x: 4,
      y: 14,
      start: 37.5,
      end: 39.2,
      classes: ['small', 'shrinking', 'expanding'],
    },
    {
      x: 0,
      y: 0,
      start: 39.4,
      end: 40.3,
      classes: ['small', 'shrinking', 'expanding'],
    },
    {
      x: 0,
      y: 0,
      start: 40.3,
      end: 42.2,
      classes: ['small', 'shrinking', 'expanding'],
    },
    {
      x: 0,
      y: 0,
      start: 42.6,
      end: 44.2,
      classes: ['small', 'shrinking', 'expanding'],
    },
    {
      x: 300,
      y: 300,
      start: 42.6,
      end: 44.2,
      classes: ['small', 'shrinking', 'expanding'],
    },
    {
      x: 300,
      y: 300,
      start: 44.5,
      end: 46.5,
      classes: ['small', 'shrinking', 'expanding'],
    },
  ],
};
