export default {
  defaults: {
    duration: 3,
    classes: ['shrinking', 'expanding'],
  },
  sequence: [
    {
      x: 20,
      y: 70,
      start: 4.15,
      end: 7,
      classes: ['small', 'shrinking', 'expanding'],
    },
    {
      x: 70,
      y: 20,
      start: 11,
      end: 13.9,
    },
    {
      x: 70,
      y: 20,
      start: 14.2,
      end: 17.2,
    },
    {
      x: 70,
      y: 20,
      start: 18.2,
      end: 20.4,
    },
    {
      x: 70,
      y: 20,
      start: 21,
      end: 23.5,
      classes: ['small', 'shrinking', 'expanding'],
    },
    {
      x: 20,
      y: 20,
      start: 27.59,
      end: 30,
      classes: ['small', 'shrinking', 'expanding'],
    },
    {
      x: 80,
      y: 80,
      start: 27.59,
      end: 30,
    },
    {
      x: 80,
      y: 80,
      start: 31,
      end: 33,
      classes: ['small', 'shrinking', 'expanding'],
    },
    {
      x: 80,
      y: 80,
      start: 33.4,
      end: 35,
      classes: ['small', 'shrinking', 'expanding'],
    },
    {
      x: 20,
      y: 80,
      start: 36.4,
      end: 38.4,
      classes: ['small', 'shrinking', 'expanding'],
    },
    {
      x: 20,
      y: 20,
      start: 37.8,
      end: 40,
      classes: ['small', 'shrinking', 'expanding'],
    },
  ],
};
